import './index.css'

import './javascript/index'
import './javascript/about'
import './javascript/collections'
import './javascript/lifehacks'
import './javascript/map'
import './javascript/remindercard'
import './javascript/hamburger'
import './javascript/promo'
