import './index.css'

import './javascript/back'
import './javascript/hamburger'
import './javascript/promo'
import './javascript/slider'
import './javascript/styleguide'
import './javascript/mindmap/trash/mindmappagetrash1'
import './javascript/mindmap/food/mindmappagefood1'
import './javascript/mindmap/food/mindmappagefood2'
import './javascript/mindmap/clothes/mindmappageclothes1'
import './javascript/mindmap/clothes/mindmappageclothes2'
import './javascript/searchandfilter'
import './javascript/maprecyclingplases/glass'
import './javascript/mappage'
