import './index.css'

import './javascript/back'
import './javascript/hamburger'
import './javascript/promo'
import './javascript/slider'
import './javascript/styleguide'
import './javascript/mindmappagetrash1'
import './javascript/mindmappagefood1'
import './javascript/searchandfilter'
